position: [25, 25]
size: [-25, -25]
drawBackground:

globalConfig: SBConfig

elements:
  
  SettingsContainer:
    gridSize: [3, 2]
    
    elements:
      KeybindContainer:
        size: [1, 2]
        
        elements:
          KeybindTextbox:
            size: [200, 20]
            
            text: keyBinds
          
          KeybindList:
            position: [0, 20]
            size: [0, -40]
            
            listName: keyEventList
            
            text: "bind:|ELEMENT|"
            text2: \$keybindings.|ELEMENT|\
          
          KeybindSetButton:
            position: [0, -1]
            size: [0, 35]
            
            toggle:
            
            text: setKeybind
            
            onClick: SBGlobalBinding
            onRelease: SBGlobalBindingR
    
      DeviceContainer:
        position: [1, 1]
        size: [2, 1]
        
        elements:
          DeviceTextbox:
            size: [0, 20]
            text: setAudio
          
          DeviceList:
            position: [0, 25]
            size: [0, -100]
            
            listName: audioDeviceNames
          
          DeviceTextbox1:
            position: [0, -76]
            size: [0, 20]
            
            text: AudioDevice1
          
          DeviceButton1:
            position: [0, -50]
            size: [0, 25]
            
            text: setAudio1
            
            onClick: SetAudio1
          
          DeviceTextbox2(0, 26, 0, 20):
            position: [0, -25]
            size: [0, 20]
            
            text: AudioDevice2
          
          DeviceButton1(0, 0, 0, 25):
            position: [0, -1]
            size: [0, 25]
            
            text: setAudio2
            
            onClick: SetAudio2
    
      SwitchContainer:
        position: [1, 0]
        
        elements:
          BindSwitchContainer:
            position: [10, 5]
            size: [300, 50]
            gridSize: [3, 2]
            
            elements:
              BindSwitchTextbox:
                size: [3, 1]
                text: BindSwitchTextbox
              
              CapsSwitch:
                position: [0, 1]
                
                text: Caps
                
                bind: UseCapslock
                onClick: SBConfigSet
                
              NumSwitch:
                position: [1, 1]
                
                text: Num
                
                bind: UseNumlock
                onClick: SBConfigSet
                
              ScrollSwitch:
                position: [2, 1]
                
                text: Scroll
                
                bind: UseScrolllock
                onClick: SBConfigSet
                
  CloseButton:
    position: [-5, 5]
    size: [80, 20]
    
    text: closeMenu
    
    onClick: GUIHide(SettingsMenu)